// @flow

export const FETCH_GEO = 'FETCH_GEO';
export const FETCH_GEO_SUCCESS = 'FETCH_GEO_SUCCESS';
export const FETCH_GEO_FAILURE = 'FETCH_GEO_FAILURE';
export const RESET_GEO = 'RESET_GEO';

export const FETCH_CURRENT_GEO = 'FETCH_CURRENT_GEO';
export const FETCH_CURRENT_GEO_SUCCESS = 'FETCH_CURRENT_GEO_SUCCESS';
export const FETCH_CURRENT_GEO_FAILURE = 'FETCH_CURRENT_GEO_FAILURE';

export const FETCH_GEO_IDS = 'FETCH_GEO_IDS';
export const FETCH_GEO_IDS_SUCCESS = 'FETCH_GEO_IDS_SUCCESS';
export const FETCH_GEO_IDS_FAILURE = 'FETCH_GEO_IDS_FAILURE';

export const GEO_REDIRECT = 'GEO_REDIRECT';

export const CHANGE_CURRENT_GEO = 'CHANGE_CURRENT_GEO';
