// @flow

export const CHANGE_VACANCIES_FILTER = 'CHANGE_VACANCIES_FILTER';
export const RESET_VACANCIES_FILTER = 'RESET_VACANCIES_FILTER';

export const HIDE_ADDITIONAL_FILTERS = 'HIDE_ADDITIONAL_FILTERS';
export const SHOW_ADDITIONAL_FILTERS = 'SHOW_ADDITIONAL_FILTERS';

export const SAVE_REQUEST_VACANCIES = 'SAVE_REQUEST_VACANCIES';
